platform :ios, '7.0'
target 'OCProject' do
pod 'Masonry', '~> 1.1.0'
pod 'YYKit', '~> 1.0.9'
pod 'FMDB', '~> 2.7.2'
end

target 'OCProjectTests' do
    pod 'Masonry', '~> 1.1.0'
    pod 'YYKit', '~> 1.0.9'
    pod 'FMDB', '~> 2.7.2'
end

target 'OCProjectUITests' do
    pod 'Masonry', '~> 1.1.0'
    pod 'YYKit', '~> 1.0.9'
    pod 'FMDB', '~> 2.7.2'
end
